name: Docker Image deployment

on:
  push:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Launcher with Gradle
        run: ./gradlew :launcher:build

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tags
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            echo "TAG=ghcr.io/thevelocloud/velocloud:master" >> $GITHUB_ENV
            echo "LATEST=ghcr.io/thevelocloud/velocloud:latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "development" ]]; then
            echo "TAG=ghcr.io/thevelocloud/velocloud:development" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image (amd64 + arm64)
        run: |
          if [[ "${GITHUB_REF_NAME}" == "master" ]]; then
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -f docker/Dockerfile \
              -t $TAG \
              -t $LATEST \
              --push .
          else
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -f docker/Dockerfile \
              -t $TAG \
              --push .
          fi
